/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProjectProjectImage from './ProjectProjectImage';

/**
 * The Project model module.
 * @module model/Project
 * @version 1.0.0
 */
class Project {
    /**
     * Constructs a new <code>Project</code>.
     * @alias module:model/Project
     * @param projectTitle {String} 
     * @param projectImage {module:model/ProjectProjectImage} 
     */
    constructor(projectTitle, projectImage) { 
        
        Project.initialize(this, projectTitle, projectImage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, projectTitle, projectImage) { 
        obj['projectTitle'] = projectTitle;
        obj['projectImage'] = projectImage;
    }

    /**
     * Constructs a <code>Project</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Project} obj Optional instance to populate.
     * @return {module:model/Project} The populated <code>Project</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Project();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('projectTitle')) {
                obj['projectTitle'] = ApiClient.convertToType(data['projectTitle'], 'String');
            }
            if (data.hasOwnProperty('projectImage')) {
                obj['projectImage'] = ProjectProjectImage.constructFromObject(data['projectImage']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Project.prototype['_id'] = undefined;

/**
 * @member {String} projectTitle
 */
Project.prototype['projectTitle'] = undefined;

/**
 * @member {module:model/ProjectProjectImage} projectImage
 */
Project.prototype['projectImage'] = undefined;






export default Project;

